### PR TITLE
Makes application scroll circular

### PR DESCRIPTION
**Pull request by rodrigues**
If you wish 👍🏼

loop

EDIT: reused the cursor logic in the others by introducing the module `Toby.Cursor`, however I couldn't test the load, it doesn't open for me even in master.

### CODE REVIEW

**Comment by ndreynolds** [comment]
Thanks, I love it!

About the load component not loading---could you check `log/debug.log` for details?  I use that to read the error messages since it's almost impossible to read any written to the stdout :smile:.   I think it's probably a match error when trying to load the VM stats; it could be your Erlang version is different than mine and the stats are returned in a slightly different way.

**Comment by rodrigues** [comment]
@ndreynolds looks like it's some problem trying to show the results: https://gist.github.com/rodrigues/d20500fa87e2f6b7ad8358c00bd779f7

I'm on Elixir 1.8.0, OTP 21.2.2, macOS 👍🏼

**Comment by ndreynolds** [comment]
@rodrigues okay, thanks.  I took a look and apparently the `weighted` value isn't always provided.  I think this should fix it: 14d486e312bd7776388d5517719d5a751a304f0b

**Comment by rodrigues** [comment]
@ndreynolds thanks, that worked 🙂

**Pull request merged**
